
// This file has been generated by the GUI designer. Do not modify.
namespace CarRepair
{
	public partial class AddRepairWindow2
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Alignment alignment4;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Alignment alignment3;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Entry VehicleOwnerEntry;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Entry RegistrationEntry;
		
		private global::Gtk.HSeparator hseparator2;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Entry VehicleTypeEntry;
		
		private global::Gtk.HSeparator hseparator3;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView DescriptionTextView;
		
		private global::Gtk.HSeparator hseparator4;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Button button1;
		
		private global::Gtk.HSeparator hseparator5;
		
		private global::Gtk.HSeparator hseparator6;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.HButtonBox hbuttonbox1;
		
		private global::Gtk.Alignment alignment2;
		
		private global::Gtk.Alignment alignment1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CarRepair.AddRepairWindow2
			this.Name = "CarRepair.AddRepairWindow2";
			this.Title = global::Mono.Unix.Catalog.GetString ("Dodavanje kvara");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child CarRepair.AddRepairWindow2.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.hbox1.Add (this.alignment4);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment4]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			this.vbox1.Add (this.alignment3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment3]));
			w2.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Ime i prezime vl.");
			this.hbox2.Add (this.label6);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label6]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.VehicleOwnerEntry = new global::Gtk.Entry ();
			this.VehicleOwnerEntry.CanFocus = true;
			this.VehicleOwnerEntry.Name = "VehicleOwnerEntry";
			this.VehicleOwnerEntry.IsEditable = true;
			this.VehicleOwnerEntry.InvisibleChar = '●';
			this.hbox2.Add (this.VehicleOwnerEntry);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.VehicleOwnerEntry]));
			w4.Position = 1;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox3.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Registracija        ");
			this.hbox3.Add (this.label7);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label7]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.RegistrationEntry = new global::Gtk.Entry ();
			this.RegistrationEntry.CanFocus = true;
			this.RegistrationEntry.Name = "RegistrationEntry";
			this.RegistrationEntry.IsEditable = true;
			this.RegistrationEntry.InvisibleChar = '●';
			this.hbox3.Add (this.RegistrationEntry);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.RegistrationEntry]));
			w8.Position = 1;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox3.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator2]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Model vozila      ");
			this.hbox4.Add (this.label8);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label8]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.VehicleTypeEntry = new global::Gtk.Entry ();
			this.VehicleTypeEntry.CanFocus = true;
			this.VehicleTypeEntry.Name = "VehicleTypeEntry";
			this.VehicleTypeEntry.IsEditable = true;
			this.VehicleTypeEntry.InvisibleChar = '●';
			this.hbox4.Add (this.VehicleTypeEntry);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.VehicleTypeEntry]));
			w12.Position = 1;
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox3]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.vbox2.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator3]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Opis kvara         ");
			this.hbox6.Add (this.label9);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label9]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.DescriptionTextView = new global::Gtk.TextView ();
			this.DescriptionTextView.CanFocus = true;
			this.DescriptionTextView.Name = "DescriptionTextView";
			this.GtkScrolledWindow.Add (this.DescriptionTextView);
			this.hbox6.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.GtkScrolledWindow]));
			w18.Position = 1;
			this.vbox4.Add (this.hbox6);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox6]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hseparator4 = new global::Gtk.HSeparator ();
			this.hseparator4.Name = "hseparator4";
			this.vbox4.Add (this.hseparator4);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator4]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Xalign = 0.7F;
			this.button1.Yalign = 0.7F;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("Spremi");
			this.hbox7.Add (this.button1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.button1]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox4.Add (this.hbox7);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox7]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hseparator5 = new global::Gtk.HSeparator ();
			this.hseparator5.Name = "hseparator5";
			this.vbox4.Add (this.hseparator5);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator5]));
			w23.Position = 3;
			w23.Expand = false;
			w23.Fill = false;
			this.vbox2.Add (this.vbox4);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox4]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator6 = new global::Gtk.HSeparator ();
			this.hseparator6.Name = "hseparator6";
			this.vbox2.Add (this.hseparator6);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator6]));
			w25.Position = 3;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.vbox5.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbuttonbox1]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			this.vbox2.Add (this.vbox5);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox5]));
			w27.Position = 4;
			w27.Expand = false;
			w27.Fill = false;
			this.vbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.vbox1.Add (this.alignment2);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment2]));
			w29.Position = 2;
			this.hbox1.Add (this.vbox1);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.hbox1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment1]));
			w31.Position = 2;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 707;
			this.DefaultHeight = 582;
			this.Show ();
			this.button1.Clicked += new global::System.EventHandler (this.onSaveClicked);
		}
	}
}
