
// This file has been generated by the GUI designer. Do not modify.
namespace CarRepair
{
	public partial class EmployeeWindow
	{
		private global::Gtk.HBox hbox17;
		
		private global::Gtk.Alignment alignment23;
		
		private global::Gtk.VBox vbox13;
		
		private global::Gtk.Alignment alignment21;
		
		private global::Gtk.Table table3;
		
		private global::Gtk.Entry birthDateEntry;
		
		private global::Gtk.Button button27;
		
		private global::Gtk.Button button29;
		
		private global::Gtk.CheckButton checkbutton1;
		
		private global::Gtk.ComboBox combobox1;
		
		private global::Gtk.Entry firstNameEntry;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.Label label16;
		
		private global::Gtk.Label label18;
		
		private global::Gtk.Label label20;
		
		private global::Gtk.Label label22;
		
		private global::Gtk.Label label24;
		
		private global::Gtk.Label label26;
		
		private global::Gtk.Label label28;
		
		private global::Gtk.Entry lastNameEntry;
		
		private global::Gtk.Entry oibEntry;
		
		private global::Gtk.Entry passwordEntry;
		
		private global::Gtk.Entry startDateEntry;
		
		private global::Gtk.Entry usernameEntry;
		
		private global::Gtk.Alignment alignment27;
		
		private global::Gtk.Alignment alignment25;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CarRepair.EmployeeWindow
			this.Name = "CarRepair.EmployeeWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Unos djelatnika");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child CarRepair.EmployeeWindow.Gtk.Container+ContainerChild
			this.hbox17 = new global::Gtk.HBox ();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.alignment23 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment23.Name = "alignment23";
			this.hbox17.Add (this.alignment23);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.alignment23]));
			w1.Position = 0;
			// Container child hbox17.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox ();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.alignment21 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment21.Name = "alignment21";
			this.vbox13.Add (this.alignment21);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.alignment21]));
			w2.Position = 0;
			// Container child vbox13.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(11)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.birthDateEntry = new global::Gtk.Entry ();
			this.birthDateEntry.CanFocus = true;
			this.birthDateEntry.Name = "birthDateEntry";
			this.birthDateEntry.IsEditable = true;
			this.birthDateEntry.InvisibleChar = '●';
			this.table3.Add (this.birthDateEntry);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3 [this.birthDateEntry]));
			w3.TopAttach = ((uint)(4));
			w3.BottomAttach = ((uint)(5));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.button27 = new global::Gtk.Button ();
			this.button27.CanFocus = true;
			this.button27.Name = "button27";
			this.button27.UseUnderline = true;
			this.button27.Label = global::Mono.Unix.Catalog.GetString ("Spremi");
			this.table3.Add (this.button27);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3 [this.button27]));
			w4.TopAttach = ((uint)(9));
			w4.BottomAttach = ((uint)(10));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.button29 = new global::Gtk.Button ();
			this.button29.CanFocus = true;
			this.button29.Name = "button29";
			this.button29.UseUnderline = true;
			this.button29.Label = global::Mono.Unix.Catalog.GetString ("Obriši");
			this.table3.Add (this.button29);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3 [this.button29]));
			w5.TopAttach = ((uint)(10));
			w5.BottomAttach = ((uint)(11));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.checkbutton1 = new global::Gtk.CheckButton ();
			this.checkbutton1.CanFocus = true;
			this.checkbutton1.Name = "checkbutton1";
			this.checkbutton1.Label = "";
			this.checkbutton1.DrawIndicator = true;
			this.checkbutton1.UseUnderline = true;
			this.table3.Add (this.checkbutton1);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3 [this.checkbutton1]));
			w6.TopAttach = ((uint)(8));
			w6.BottomAttach = ((uint)(9));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.combobox1 = global::Gtk.ComboBox.NewText ();
			this.combobox1.Name = "combobox1";
			this.table3.Add (this.combobox1);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3 [this.combobox1]));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.firstNameEntry = new global::Gtk.Entry ();
			this.firstNameEntry.CanFocus = true;
			this.firstNameEntry.Name = "firstNameEntry";
			this.firstNameEntry.IsEditable = true;
			this.firstNameEntry.InvisibleChar = '●';
			this.table3.Add (this.firstNameEntry);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3 [this.firstNameEntry]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Odaberi djelatnika:");
			this.table3.Add (this.label12);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3 [this.label12]));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Ime:");
			this.table3.Add (this.label14);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3 [this.label14]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Prezime:");
			this.table3.Add (this.label16);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table3 [this.label16]));
			w11.TopAttach = ((uint)(2));
			w11.BottomAttach = ((uint)(3));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("OIB:");
			this.table3.Add (this.label18);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table3 [this.label18]));
			w12.TopAttach = ((uint)(3));
			w12.BottomAttach = ((uint)(4));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Datum rođenja:");
			this.table3.Add (this.label20);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table3 [this.label20]));
			w13.TopAttach = ((uint)(4));
			w13.BottomAttach = ((uint)(5));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label22 = new global::Gtk.Label ();
			this.label22.Name = "label22";
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("Početak rada:");
			this.table3.Add (this.label22);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table3 [this.label22]));
			w14.TopAttach = ((uint)(7));
			w14.BottomAttach = ((uint)(8));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label24 = new global::Gtk.Label ();
			this.label24.Name = "label24";
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("Korisnicko ime:");
			this.table3.Add (this.label24);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table3 [this.label24]));
			w15.TopAttach = ((uint)(5));
			w15.BottomAttach = ((uint)(6));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label26 = new global::Gtk.Label ();
			this.label26.Name = "label26";
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString ("Lozinka:");
			this.table3.Add (this.label26);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table3 [this.label26]));
			w16.TopAttach = ((uint)(6));
			w16.BottomAttach = ((uint)(7));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label28 = new global::Gtk.Label ();
			this.label28.Name = "label28";
			this.label28.LabelProp = global::Mono.Unix.Catalog.GetString ("Administrator");
			this.table3.Add (this.label28);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table3 [this.label28]));
			w17.TopAttach = ((uint)(8));
			w17.BottomAttach = ((uint)(9));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.lastNameEntry = new global::Gtk.Entry ();
			this.lastNameEntry.CanFocus = true;
			this.lastNameEntry.Name = "lastNameEntry";
			this.lastNameEntry.IsEditable = true;
			this.lastNameEntry.InvisibleChar = '●';
			this.table3.Add (this.lastNameEntry);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table3 [this.lastNameEntry]));
			w18.TopAttach = ((uint)(2));
			w18.BottomAttach = ((uint)(3));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.oibEntry = new global::Gtk.Entry ();
			this.oibEntry.CanFocus = true;
			this.oibEntry.Name = "oibEntry";
			this.oibEntry.IsEditable = true;
			this.oibEntry.InvisibleChar = '●';
			this.table3.Add (this.oibEntry);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table3 [this.oibEntry]));
			w19.TopAttach = ((uint)(3));
			w19.BottomAttach = ((uint)(4));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.passwordEntry = new global::Gtk.Entry ();
			this.passwordEntry.CanFocus = true;
			this.passwordEntry.Name = "passwordEntry";
			this.passwordEntry.IsEditable = true;
			this.passwordEntry.Visibility = false;
			this.passwordEntry.InvisibleChar = '●';
			this.table3.Add (this.passwordEntry);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table3 [this.passwordEntry]));
			w20.TopAttach = ((uint)(6));
			w20.BottomAttach = ((uint)(7));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.startDateEntry = new global::Gtk.Entry ();
			this.startDateEntry.CanFocus = true;
			this.startDateEntry.Name = "startDateEntry";
			this.startDateEntry.IsEditable = true;
			this.startDateEntry.InvisibleChar = '●';
			this.table3.Add (this.startDateEntry);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table3 [this.startDateEntry]));
			w21.TopAttach = ((uint)(7));
			w21.BottomAttach = ((uint)(8));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.usernameEntry = new global::Gtk.Entry ();
			this.usernameEntry.CanFocus = true;
			this.usernameEntry.Name = "usernameEntry";
			this.usernameEntry.IsEditable = true;
			this.usernameEntry.InvisibleChar = '●';
			this.table3.Add (this.usernameEntry);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table3 [this.usernameEntry]));
			w22.TopAttach = ((uint)(5));
			w22.BottomAttach = ((uint)(6));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox13.Add (this.table3);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.table3]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.alignment27 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment27.Name = "alignment27";
			this.vbox13.Add (this.alignment27);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.alignment27]));
			w24.Position = 2;
			this.hbox17.Add (this.vbox13);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.vbox13]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.alignment25 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment25.Name = "alignment25";
			this.hbox17.Add (this.alignment25);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.alignment25]));
			w26.Position = 2;
			this.Add (this.hbox17);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 795;
			this.DefaultHeight = 623;
			this.Show ();
			this.combobox1.Changed += new global::System.EventHandler (this.OnCombobox1Changed);
			this.button29.Clicked += new global::System.EventHandler (this.OnButton29Clicked);
			this.button27.Clicked += new global::System.EventHandler (this.OnButton27Clicked);
		}
	}
}
